/********************************************************************************************/
/* Macro cleaning default log, html and lst files generated by default in current directory */
/* of the program executed.                                                                 */
/********************************************************************************************/

%macro clean_log_outputs_in_curdir();
	data _null_;
		parent_dir=substr("&_sasprogramfile", 1, length("&_sasprogramfile") 
			- length(scan("&_sasprogramfile", -1, '/'))-1);
		call symputx('parent_dir', parent_dir);
	run;

	DATA _NULL_;
		rc=filename('spec', "&parent_dir");
		did=dopen('spec');
		do i=1 to dnum(did);
			file_name=dread(did, i);
			if lowcase(scan(file_name, -1, '.')) in ("log", "lst", "html") then do;
				fname=cats("&parent_dir./", file_name);
				put fname;
				rc=filename('fref', fname);
				rc=fdelete('fref');
				rc=filename('fref');
			end;
		end;
	RUN;
%mend clean_log_outputs_in_curdir;


%clean_log_outputs_in_curdir();

